### ISSUE TITLE
Subscribe to multiple Services

### ISSUE THREAD

**Issue by CoreCPU** [devcartel/api#1]
Hi,

I am trying to find out whether it is possible to subscribe to multiple services per session ?
I can not find a way to set the ServiceName programmatically.
The only way i found to specify the service name is in the config file.

How would i go about subscribing to multiple services as opposed to the single one specified in the config file ?

Thanks a lot...

Kind Regards,

Alain

**Comment by wiwat-tharateeraparb** [comment]
Usage:
```python
pyrfa.setServiceName("SERVICE1")
pyrfa.marketPriceRequest("RIC1")
pyrfa.setServiceName("SERVICE2")
pyrfa.marketPriceRequest("RIC2")
```
