### ISSUE TITLE
can you pull data similar to TR functions?

### ISSUE THREAD

**Issue by mstellaris** [devcartel/api#10]
does pyrfa allow for similar data retrieval as one would do with the TR functions through excel?

**Comment by wiwat-tharateeraparb** [comment]
In short, yes it can. You would need know the data feed server IP address
and username. PyRFA also allows retrieving data in other ways that Excel
cannot do such as level-2 data (order book) and timeseries.

--
Wiwat Tharateeraparb
www.devcartel.com | wiwat.t@devcartel.com
+668 9500 9810

On 24 Jun 2015, at 12:40, mstellaris <notifications@github.com> wrote:

does pyrfa allow for similar data retrieval as one would do with the TR
functions through excel?

—
Reply to this email directly or view it on GitHub
<https://github.com/devcartel/api/issues/10>.

**Comment by mstellaris** [comment]
hi wiwat,
thanks for the answer. to be more specific, I have provided some examples of TR function used in Excel:

TR("2628.HK","TR.EventStartDate.date","EventType=RES"))
TR.DivExDate(SDate=-3M EDate=1AY DateType=PD)
TR.DivUnadjustedNet(SDate=-3M EDate=1AY DateType=PD)

Could you please comment if it is possible or not to request such dividend data through your library?

Thanks!

**Comment by wiwat-tharateeraparb** [comment]
Hi, I am not sure if it can get that dividend data really. It looks like it's  timeseries data which I think PyRFA will not be able to retrieve those.
