### ISSUE TITLE
Does PyRFA support conflation for streaming?

### ISSUE THREAD

**Issue by peervm** [devcartel/api#11]

**Comment by wiwat-tharateeraparb** [comment]
PyRFA does not combine market data from two or more services on its own. However it does support service resiliency through Service Group where it subscribes to two or more services and give you the data from the first available service.

**Comment by peervm** [comment]
Sorry, I might have used the wrong term, but I thought conflation means that if multiple updates are queued up in the event queue then earlier updates are ignored and conflated into a single update when they are finally dispatched. (I.e. only the latest update dictionary is returned)

**Comment by wiwat-tharateeraparb** [comment]
Hi, PyRFA does not support this.

**Comment by wiwat-tharateeraparb** [comment]
PyRFA cannot conflate updates at this version. I know this can be done at
ADH level. Will explore the possibility though.

--
Wiwat Tharateeraparb
www.devcartel.com | wiwat.t@devcartel.com
+668 9500 9810

On 1 Jul 2015, at 17:34, peervm <notifications@github.com> wrote:

Sorry, I might have used the wrong term, but I thought conflation means
that if multiple updates are queued up in the event queue then earlier
updates are ignored and conflated into a single update when they are
finally dispatched. (I.e. only the latest update dictionary is returned)

—
Reply to this email directly or view it on GitHub
<https://github.com/devcartel/api/issues/11#issuecomment-117587715>.

**Comment by peervm** [comment]
Understood - thanks for the prompt reply.

**Comment by wiwat-tharateeraparb** [comment]
Good news, the next release of PyRFA will include a feature called "pause/resume" with new commands `pyrfa.pause("RIC1,RIC2")`,`pyrfa.resume("RIC1,RIC2")`,`pyrfa.pauseAll()` and `pyrfa.resumeAll()`. Currently, we have tested this feature and be able to conflate updates with variable conflation time.

To achieve update conflation, we can use pause/resume with command:

```python
p.resumeAll()
p.dispatchEventQueue(50)
p.pauseAll()
```

Individual updates during a pause
```
IDN_RDF_SDS - JPY=
     EURO_NETCH 0.21
          MTYPE UPDATE
            RIC JPY=
        SERVICE IDN_RDF_SDS


IDN_RDF_SDS - JPY=
      PCTCHG_6M 4.97
        SERVICE IDN_RDF_SDS
            RIC JPY=
          MTYPE UPDATE
     PCTCHG_YTD -2.51
     PCTCHG_MTD 0.47
      PCTCHG_3M 1.34
```
After resuming, updates are conflated to:
```
IDN_RDF_SDS - JPY=
      PCTCHG_6M 4.97
        SERVICE IDN_RDF_SDS
     EURO_NETCH 0.21
     PCTCHG_MTD 0.47
          MTYPE UPDATE
     PCTCHG_YTD -2.51
            RIC JPY=
      PCTCHG_3M 1.34
```

**Comment by peervm** [comment]
Awesome - that is exactly what I am looking for.

**Comment by wiwat-tharateeraparb** [comment]
Just released 8.0.0.1 and it supports pause/resume. Checkout `examples/conflation.py` for using pause/resume to make update conflation. Cheers.

**Comment by peervm** [comment]
Great stuff -and thanks for the fast turn around time. Much appreciated.

I just realized that 8.0.0.1 doesn't support windows 32bit 2.7 anymore. Unfortunately due to a couple of proprietary yet essential libraries, I am unable to upgrade. Is the decision to drop 32bit builds permanent, because I am sure other people must have the same problem.

Thanks.

**Comment by ukrit-himakoon** [comment]
Hello

According to RFA 8.0, it currently supports only 64 bit machine. So,
PyRFA8.0 will follow this as well for the future release.

Good news that we're working to release PyRFA7.6.1.3 which will support
windows 32 bit machine.
We'll keep you posted once the package is available for the download.

However, we still encourage you to upgrade to windows 64 bit in the future.

Thanks for using PyRFA
Ukrit H.

**Comment by ukrit-himakoon** [comment]
Hello,

I would like to inform you that we have released RFA7.6.1.3 which supports
windows 32 bit today. Definitely, this version also support pause/resume
capability as requested.

Please noted that since PyRFA8.0.0 there's an update which simplify the
output data so now the message exposes from dispatchEventQueue will be the
dictionary as in the example below, you need to update your source code to
support this data format as well.

>>> p.marketPriceRequest('EUR=')
>>> p.dispatchEventQueue()
{'MTYPE':'REFRESH','RIC':'EUR=','SERVICE':'IDN_RDF_SDS'}
{'MTYPE':'IMAGE','RIC':'EUR=','SERVICE':'IDN_RDF_SDS','ASK':1.3712,'BID':1.3709,...}


Please visit our download page below:

http://devcartel.com/pyrfa

Best regards,
Ukrit H.
