### ISSUE TITLE
Rounding when retrieving TS1 data

### ISSUE THREAD

**Issue by louisChiffre** [devcartel/api#12]
When retrieving TS1 data for some rics, TS1 quotes are sometimes  rounded aggressively. For example, for the ric JPY1MFSR=, the data is rounded to the third decimal

DATE,CLOSE
2015/07/31,0.056
2015/06/30,0.059
2015/05/31,0.064

when the real data point for 2015/07/31 is 0.05643.

Is there anything that can be done to control the rounding?

**Comment by wiwat-tharateeraparb** [comment]
Seems to be a bug that limits decimal point to just three. Will fix in the next release. Thanks.

**Comment by louisChiffre** [comment]
That's great, thanks. When do you plan to release the fix?

**Comment by wiwat-tharateeraparb** [comment]
Next release should be on 21 August. And it will include this fix.

**Comment by louisChiffre** [comment]
Very good. Thank you for the information.

**Comment by wiwat-tharateeraparb** [comment]
Just released 8.0.0.2 which includes this fix.

**Comment by louisChiffre** [comment]
I tested it and it is fixed indeed. Thanks.
