### ISSUE TITLE
Pyrfa does not clean up properly

### ISSUE THREAD

**Issue by ihateselectingusernames** [devcartel/api#13]
p = pyrfa.Pyrfa()
There is no elegant way to clean up memory occupied by "p".
Killing the process seems to be the only way. "del p" doesn't work.

Please provide a reliable way to clean up this object.

**Comment by wiwat-tharateeraparb** [comment]
We detect a memory leak in data dictionary related function where dictionary is not properly removed when object is destroyed. Will fix this in the next release. 

Having said that, with the fix in place, the "del p" command still does not release full memory back to the OS. It depends on Python object management.

**Comment by ihateselectingusernames** [comment]
Good to know. Thanks for the planned fix.

**Comment by wiwat-tharateeraparb** [comment]
Just released 8.0.0.2 which includes this fix.

**Comment by ihateselectingusernames** [comment]
Thank you very much. We only have Python 2.7 (32bit) - any chance you can make a release for 32bit version?

**Comment by ukrit-himakoon** [comment]
Hello,

Could you please clarify what platform you're using?

Best regards,
Ukrit H.

**Comment by ukrit-himakoon** [comment]
Please clarify if the platform is windows or linux with the specific version.

**Comment by ihateselectingusernames** [comment]
Microsoft Windows Server 2003 - Enterprise Edition, Service Pack 2

**Comment by ihateselectingusernames** [comment]
I've been using 7.6 successfully on this machine - except the memory issue. I can't really upgrade the python to 64 bit even if the machine allows it - because it is difficult to get it in my organization.

**Comment by ihateselectingusernames** [comment]
Let me give you a little bit more detail - since you guys are quite fast and I'm feeling hopeful. I have this real-time (almost) app that frequently fetches prices from RMDS (DTS/ATS) servers. When I try to create one session and keep reusing it, my app just hangs forever without any trace. When I try to re-initialize session every time I want to fetch prices, it keeps inflating the memory of my windows service (pythonservice) and I have to restart this service every now and then (automatically of course :) )

I can't copy paste the actual code so in pseudocode terms:

session=Pyrfa();  # And do login/initialization etc.
for all RICs:
 session.marketPriceRequest(RIC)

while a reasonable amount of time has passed or all updates have been received:
    updates = session.dispatchEventQueue(1000)
    check updates

I'm sure there are other people out there looking for this package to work with Python 2.x, 32bit. Continuing a release in that branch might not be a bad idea. 
Thanks a lot for all your effort!

**Comment by ihateselectingusernames** [comment]
Will there be a Windows (x86 + Python2.7) release for latest version by any chance?

**Comment by ukrit-himakoon** [comment]
Hello,

We're working into this.

Will update you once it's available.

**Comment by ukrit-himakoon** [comment]
Hello,

I would like to inform you that we have released RFA7.6.1.3 which supports
windows 32 bit today. We have fixed most of the memory leak issue for you.

Please noted that since PyRFA8.0.0 there's an update which simplifies the
output data so now the message exposes from dispatchEventQueue will be the
dictionary as in the example below, you need to update your source code to
support this data format as well.

>>> p.marketPriceRequest('EUR=')
>>> p.dispatchEventQueue()
{'MTYPE':'REFRESH','RIC':'EUR=','SERVICE':'IDN_RDF_SDS'}
{'MTYPE':'IMAGE','RIC':'EUR=','SERVICE':'IDN_RDF_SDS','ASK':1.3712,'BID':1.3709,...}


Please visit our download page below:

http://devcartel.com/pyrfa

Best regards,
Ukrit H.

**Comment by wiwat-tharateeraparb** [comment]
Since version 8.0.0, Thomson Reuters decided to drop support for Win32 and RHEL5. So we will be maintaining 7.6.1 for Win32 and RHEL5 instead. Any bug fixes in 8.0.0 series will be back ported to 7.6.1 as well. Having said that, there are some features that you can do with 8.0.0 but not with 7.6.1.

**Comment by ihateselectingusernames** [comment]
Thanks a lot guys. I can live with the functionalities of 7.6 for now. I haven't had time to test it yet. I'll let you know my feedback soon.
