### ISSUE TITLE
How to become a posting consumer ?

### ISSUE THREAD

**Issue by CoreCPU** [devcartel/api#4]
While pyRFA allowes one to contribute, it would seem one can only do this by becoming a provider.
I have not found a way to post/publish as a consumer. 
Does pyRFA allow this ?

**Comment by wiwat-tharateeraparb** [comment]
Good news. The next release of PyRFA will have OMMPost capability.

**Comment by wiwat-tharateeraparb** [comment]
PyRFA 8.0.0.1 supports OMM posting. Cheers.
