### ISSUE TITLE
RIC without exchange code

### ISSUE THREAD

**Issue by hoshoo21** [devcartel/api#7]
How would i search for equity, without specifying it exchange code. I am not maintaining any msd so its harder for achieve this

**Comment by ukrit-himakoon** [comment]
Hello Hoshoo21,

The API does not support this kind of usage. Normally, the list of RICs
(Reuters Instrument Code) and the permission to subscribe the data from the
service could be informed by TR.

Best regards,
Ukrit H.

**Comment by hoshoo21** [comment]
Can you suggest me anything (apart from API and TR), that would help me to achieve this. 
Currently i have implemented Activ FInancial API in my solution, and i don't need to bother to specify Exchange code in my current solution.

**Comment by wiwat-tharateeraparb** [comment]
Not sure about your question though but you are able to search a RIC from http://www.reuters.com/finance/stocks

**Comment by hoshoo21** [comment]
Thanks for response, i have thought about the reuters symbol lookup but i think its overhead on application (making request to symbol lookup of reuters for getting exchange code and then constructing RIC from it and then sending original request). 
Here is what my solution is currently doing, user enters symbol (i.e. GOOG) in back end, i append "."(i.e. GOOG.) and then send request  to Activ FInancials. Activ financial do rest for me(identifying primary exchange of symbol) .
Now i want to do is that only making one requesting and appending exchange code (i.e. GOOG.O, MCD.N) before sending that request
