### ISSUE TITLE
No source code 

### ISSUE THREAD

**Issue by jamesblackburn** [devcartel/api#8]
There's a statement:

    Will be free software under MIT license

Is, or will, the source code be available for the ```rfa.so```?  Without it, it doesn't look like it's possible to modify the implementation.

**Comment by wiwat-tharateeraparb** [comment]
Hi,

Due to the agreement with Thomson Reuters, we are not at liberty to distribute its RFA libraries. We just thought that the MIT license will allow users to freely use PyRFA worry free.
